// A1R Phase 6 — contract schema artifact + fingerprint invariance.
//
// The checked-in `contracts/content-document@1.schema.json` MUST be byte-identical
// to what `pnpm a1r:emit-contract` produces from the effective Zod schema. If a
// future PR touches the schema without regenerating the artifact, this gate fires.
//
// The fingerprint sha256 must match the schema bytes. The fingerprint itself is
// recorded in the certification report — this test asserts the byte-artifact
// underneath.

import { describe, expect, it } from "vitest";
import { createHash } from "node:crypto";
import { readFileSync, existsSync } from "node:fs";
import { z } from "zod";

import { ContentDocumentSchema } from "@/lib/content-surface-engine/contract/content-document";

const ARTIFACT_PATH = "contracts/content-document@1.schema.json";

function sortKeys(v: unknown): unknown {
  if (Array.isArray(v)) return v.map(sortKeys);
  if (v && typeof v === "object") {
    const out: Record<string, unknown> = {};
    for (const k of Object.keys(v as Record<string, unknown>).sort()) {
      out[k] = sortKeys((v as Record<string, unknown>)[k]);
    }
    return out;
  }
  return v;
}

function fingerprint(bytes: string): string {
  return createHash("sha256").update(bytes).digest("hex");
}

describe("A1R — contract schema artifact", () => {
  it("contracts/content-document@1.schema.json exists", () => {
    expect(existsSync(ARTIFACT_PATH)).toBe(true);
  });

  it("artifact is byte-identical to freshly generated bytes", () => {
    const onDisk = readFileSync(ARTIFACT_PATH, "utf8");
    const regenerated =
      JSON.stringify(
        sortKeys(
          z.toJSONSchema(ContentDocumentSchema, {
            io: "input",
            unrepresentable: "throw",
          }),
        ),
        null,
        2,
      ) + "\n";
    if (onDisk !== regenerated) {
      throw new Error(
        `contracts/content-document@1.schema.json is out of date. Run \`pnpm a1r:emit-contract\` to refresh. onDisk=${onDisk.length}B regenerated=${regenerated.length}B`,
      );
    }
  });

  it("fingerprint is deterministic across two invocations of the same bytes", () => {
    const bytes = readFileSync(ARTIFACT_PATH, "utf8");
    expect(fingerprint(bytes)).toBe(fingerprint(bytes));
  });

  it("has a stable sha256 fingerprint that a downstream vendorer can pin", () => {
    const bytes = readFileSync(ARTIFACT_PATH, "utf8");
    const hex = fingerprint(bytes);
    // Format check ONLY — the actual value is recorded in the A1R certification
    // report and in the PR body. Locking a specific value HERE would make every
    // legitimate schema evolution break tests before humans have a chance to
    // update the report.
    expect(hex).toMatch(/^[0-9a-f]{64}$/);
  });
});
